CREATE DATABASE IF NOT EXISTS companydb;

CREATE TABLE employee (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    salary INT DEFAULT NULL,
    PRIMARY KEY(id)
);

DESCRIBE employee;